#ifndef __xmlstring_h__
#define __xmlstring_h__

/* Do not edit this file, it should be used as it is. If you feel you need any changes,
 * please discuss it first with Vladimir.Cerny@cern.ch
 * This file should be included in the c programms, never in c++ programs, where
 * xmlstring.hpp should be used instead
 */

#ifdef XML

#define XMLSTRING 100

/* xmlchar is to be used instead of char in configuration strings.
 * all char[] should have the same maximal length and defined as
 * xmlchar[XMLSTRING]
 * When converted to c++ these will be wrapped by xmlstring class
 * so that the resulting xml file contains human readable strings of characters and not
 * displayed as array of insigned 8 bit numbers
 */

typedef char xmlchar;

#endif

#endif /* __xmlstring_h__ */
